// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: org/saveole/greeting_service.proto
// Protobuf Java Version: 4.31.1

package org.saveole.grpc.greeting;

@com.google.protobuf.Generated
public interface HelloReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.saveole.grpc.greeting.HelloReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 1;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
