// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: org/saveole/user_service.proto
// Protobuf Java Version: 4.31.1

package org.saveole.grpc.user;

@com.google.protobuf.Generated
public interface UserOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.saveole.grpc.user.User)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1;</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>string name = 2;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 2;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string email = 3;</code>
   * @return The email.
   */
  java.lang.String getEmail();
  /**
   * <code>string email = 3;</code>
   * @return The bytes for email.
   */
  com.google.protobuf.ByteString
      getEmailBytes();

  /**
   * <code>repeated string phone_numbers = 4;</code>
   * @return A list containing the phoneNumbers.
   */
  java.util.List<java.lang.String>
      getPhoneNumbersList();
  /**
   * <code>repeated string phone_numbers = 4;</code>
   * @return The count of phoneNumbers.
   */
  int getPhoneNumbersCount();
  /**
   * <code>repeated string phone_numbers = 4;</code>
   * @param index The index of the element to return.
   * @return The phoneNumbers at the given index.
   */
  java.lang.String getPhoneNumbers(int index);
  /**
   * <code>repeated string phone_numbers = 4;</code>
   * @param index The index of the value to return.
   * @return The bytes of the phoneNumbers at the given index.
   */
  com.google.protobuf.ByteString
      getPhoneNumbersBytes(int index);
}
