// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: org/saveole/user_service.proto
// Protobuf Java Version: 4.31.1

package org.saveole.grpc.user;

@com.google.protobuf.Generated
public final class UserServiceProto {
  private UserServiceProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 31,
      /* patch= */ 1,
      /* suffix= */ "",
      UserServiceProto.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_saveole_grpc_user_User_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_saveole_grpc_user_User_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_saveole_grpc_user_GetUserRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_saveole_grpc_user_GetUserRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_saveole_grpc_user_GetUserResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_saveole_grpc_user_GetUserResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\036org/saveole/user_service.proto\022\025org.sa" +
      "veole.grpc.user\"F\n\004User\022\n\n\002id\030\001 \001(\t\022\014\n\004n" +
      "ame\030\002 \001(\t\022\r\n\005email\030\003 \001(\t\022\025\n\rphone_number" +
      "s\030\004 \003(\t\"\034\n\016GetUserRequest\022\n\n\002id\030\001 \001(\t\"<\n" +
      "\017GetUserResponse\022)\n\004user\030\001 \001(\0132\033.org.sav" +
      "eole.grpc.user.User2g\n\013UserService\022X\n\007Ge" +
      "tUser\022%.org.saveole.grpc.user.GetUserReq" +
      "uest\032&.org.saveole.grpc.user.GetUserResp" +
      "onseB+\n\025org.saveole.grpc.userB\020UserServi" +
      "ceProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_org_saveole_grpc_user_User_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_org_saveole_grpc_user_User_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_org_saveole_grpc_user_User_descriptor,
        new java.lang.String[] { "Id", "Name", "Email", "PhoneNumbers", });
    internal_static_org_saveole_grpc_user_GetUserRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_org_saveole_grpc_user_GetUserRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_org_saveole_grpc_user_GetUserRequest_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_org_saveole_grpc_user_GetUserResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_org_saveole_grpc_user_GetUserResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_org_saveole_grpc_user_GetUserResponse_descriptor,
        new java.lang.String[] { "User", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
