// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: org/saveole/user.proto
// Protobuf Java Version: 4.31.1

package org.saveole.model;

@com.google.protobuf.Generated
public interface GetUserResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.saveole.model.GetUserResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.org.saveole.model.User user = 1;</code>
   * @return Whether the user field is set.
   */
  boolean hasUser();
  /**
   * <code>.org.saveole.model.User user = 1;</code>
   * @return The user.
   */
  User getUser();
  /**
   * <code>.org.saveole.model.User user = 1;</code>
   */
  UserOrBuilder getUserOrBuilder();
}
