// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: org/saveole/greeting_service.proto
// Protobuf Java Version: 4.31.1

package org.saveole.grpc;

@com.google.protobuf.Generated
public final class GreetingServiceProto {
  private GreetingServiceProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 31,
      /* patch= */ 1,
      /* suffix= */ "",
      GreetingServiceProto.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_saveole_grpc_HelloRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_saveole_grpc_HelloRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_saveole_grpc_HelloReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_saveole_grpc_HelloReply_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\"org/saveole/greeting_service.proto\022\020or" +
      "g.saveole.grpc\"\034\n\014HelloRequest\022\014\n\004name\030\001" +
      " \001(\t\"\035\n\nHelloReply\022\017\n\007message\030\001 \001(\t2[\n\017G" +
      "reetingService\022H\n\010SayHello\022\036.org.saveole" +
      ".grpc.HelloRequest\032\034.org.saveole.grpc.He" +
      "lloReplyB*\n\020org.saveole.grpcB\024GreetingSe" +
      "rviceProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_org_saveole_grpc_HelloRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_org_saveole_grpc_HelloRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_org_saveole_grpc_HelloRequest_descriptor,
        new String[] { "Name", });
    internal_static_org_saveole_grpc_HelloReply_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_org_saveole_grpc_HelloReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_org_saveole_grpc_HelloReply_descriptor,
        new String[] { "Message", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
