// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: org/saveole/greeting_service.proto
// Protobuf Java Version: 4.31.1

package org.saveole.grpc;

@com.google.protobuf.Generated
public interface HelloRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.saveole.grpc.HelloRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  String getName();
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();
}
